### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by gusfaria** [Metric/Atom-Auto-Uglify#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-auto-uglify](https://github.com/Metric/Atom-Auto-Uglify) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/addison/.atom/packages/atom-auto-uglify/lib/auto-uglify.coffee:10

TypeError: Cannot read property 'indexOf' of undefined
  at compile (/Users/addison/.atom/packages/atom-auto-uglify/lib/auto-uglify.coffee:10:16)
  at atom-workspace.<anonymous> (/Users/addison/.atom/packages/atom-auto-uglify/lib/auto-uglify.coffee:24:48)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -0:15.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:14.5 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.4 core:move-right (atom-text-editor.editor.is-focused)
     -0:14.1 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:13.8 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:13.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.8 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.5 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.4 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:06.7 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:06.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.3 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.3 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:05.1 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:00.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "autocomplete-snippets",
      "autosave",
      "command-palette",
      "autocomplete-plus",
      "autocomplete-paths"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-auto-uglify, v0.2.0
atom-color-highlight, v2.0.6
change-case, v0.4.0
language-haml, v0.14.0
open-last-project, v0.1.1
scroll-past-end, v0.1.9

# Dev
No dev packages
```

/cc @atom/core

**Comment by Metric** [comment]
This has already been fixed in version 0.4.0. Please update your copy of atom-auto-uglify in atom. Thanks.
