### ISSUE TITLE
Support for ES6+

### ISSUE THREAD

**Issue by xavierfoucrier** [Metric/Atom-Auto-Uglify#8]
Unable to use the `let` keyword, this code fails to compile: `let variable = "test";`

The package throw this error:
_SyntaxError: Unexpected token: name (variable)
    at JS_Parse_Error.get (eval at <anonymous> (.atom\packages\atom-auto-uglify\node_modules\uglify-js\tools\node.js:1:1), <anonymous>:86:23)
    at Local\atom\app-1.22.0\resources\app\node_modules\notifications\lib\main.js:62:39
    at Function.module.exports.Emitter.simpleDispatch (Local\atom\app-1.22.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (Local\atom\app-1.22.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Local\atom\app-1.22.0\resources\app\src\atom-environment.js:950:31
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (Local\atom\app-1.22.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (Local\atom\app-1.22.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (Local\atom\app-1.22.0\resources\app\src\window-event-handler.js: 100:42)
    at HTMLDocument.<anonymous> (Local\atom\app-1.22.0\resources\app\src\window-event-handler.js:3:65)_

**Comment by Metric** [comment]
Looks like the uglify version needs to be updated to uglify2@3 and add
uglify-es to support both ecma 5 and ecma 6+.

Will have to take a look at it, since the api of uglify was changed in
uglify2@3.

**Comment by xavierfoucrier** [comment]
Hi! Thanks for your reply, I will check that today and come back soon :+1:

**Comment by xavierfoucrier** [comment]
Yep, agree with you. The package needs to add Uglify-ES to support ES6+. https://www.npmjs.com/package/uglify-es

**Comment by Metric** [comment]
Xavier this should now be fixed. Please update to 0.7.1 via Atom and let me know if that fixes it properly.

**Comment by xavierfoucrier** [comment]
Oops, seems that the javascript output is broken. When I compile my code without using any ES6+ keywords, it works, but when I type for example `const e = "f"`, the output just return `undefined` in the `.min.js`.

Note that the compilation works fine: Atom doesn't display any error message.

**Comment by Metric** [comment]
It is working for me with that same const e = "f". What other packages do you have installed?

Try uninstalling the package and reinstalling it fresh.

I am using the latest version of Atom on Windows 10 for testing. With only my package installed, besides the default ones that come with Atom.

**Comment by xavierfoucrier** [comment]
Will try a fresh install tomorrow. 😉

**Comment by xavierfoucrier** [comment]
Hi @Metric! I have try a fresh install and... that's it, it works fine :+1: ! Seems that the update process did not update the package files properly. Thanks for you quick fix. I close the issue.
